strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.134'

pool:
  vmImage: $(imageName)

steps:
- script: |
    sh .ci/install.sh $(Agent.OS)
  displayName: "Setup environment"

- script: |
    sh .ci/test.sh $(Agent.OS)
  displayName: "Test"